#pragma once

#include "calendar.h"
#include "character_id.h"
#include "coordinates.h"
#include "coop_input_window.h"

#include <cstdint>
#include <atomic>
#include <optional>
#include <string>

enum class coop_mode : uint8_t {
    none = 0,
    host = 1,
    client = 2,
};

struct coop_session {
    coop_mode mode = coop_mode::none;
    std::string partner_name;
    std::atomic<int> partner_ping_ms{0}; ///< RTT ms; written by IO thread, read by main thread
    /// EWMA of the wall-clock cost of this side's own world tick, in ms.
    /// Main-thread only; written by the co-op main loop in main.cpp.
    coop_tick_cost_tracker local_tick_cost;
    /// Partner-reported tick cost in ms.  Written by the host's receiver thread from
    /// client_status, and by the client's main thread from sync — atomic like partner_ping_ms.
    std::atomic<int> partner_tick_ms{0};
    std::string session_token;  ///< UUID generated by host, sent in world_seed, used for reconnect
    character_id proxy_npc_id;

    /// B3 Phase 9: set to the attacked creature's abs position by autoattack() on success;
    /// cleared to nullopt at autoattack() entry so failed attacks relay nothing.
    /// Only written by autoattack() — does NOT alias last_target_pos (shared by fire/throw).
    std::optional<tripoint_abs_ms> last_autoattack_target;

    // F1: partner vitals — written by apply_sync() / receiver_loop()
    int partner_hp_pct = 100;
    int partner_stamina_pct = 100;
    std::string partner_activity_str;
    tripoint_abs_ms partner_abs_pos{};

    // F4: shared overmap marker
    std::optional<tripoint_abs_omt> shared_mark;
    std::string shared_mark_label;

    // F6: high-five emote cooldown
    time_point last_high_five_turn = calendar::before_time_starts;

    // G2: client downed state (written on client side)
    bool is_downed = false;

    // Dimension ID captured at session start — safe to read from background threads.
    std::string dimension_id;

    auto is_host() const -> bool { return mode == coop_mode::host; }
    auto is_client() const -> bool { return mode == coop_mode::client; }
    auto is_coop() const -> bool { return mode != coop_mode::none; }

    /// Global singleton — constructed on first use, never destroyed.
    static auto get() -> coop_session&; // *NOPAD*
};

